version: '3'
services:
    web:
        stdin_open: true
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "5000:3000"
        volumes:
            - /app/node_modules/
            - /c/Users/c_and/frontend:/app

            services:
    test:
       stdin_open: true
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes:
              - /app/node_modules/
              - /c/Users/c_and/frontend:/app

        command: ["npm","run","test"] 
            



