# Using existing docker image as a base
FROM node:alpine

WORKDIR '/app'

# Download and Install a Dependency
COPY package.json .

RUN npm install
RUN ls -l
COPY . .

# Tell the image what to do when it starts as a comander
CMD ["npm", "run","start"] 