# Using existing docker image as a base
FROM node: alpine as builder

WORKDIR '/app'

# Download and Install a Dependency
COPY ./package.json ./

RUN npm install
COPY ./ ./

RUN npm run build

FROM nginx

COPY --from=builder /app/build /usr/share/nginx/html
# Tell the image what to do when it starts as a comander
CMD ["npm","run","start"] 